### ISSUE TITLE
Configuration does not work for latest K8S version

### ISSUE THREAD

**Issue by kaharon-ntx** [logzio/logz-docs#754]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ x] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: https://docs.logz.io/user-guide/distributed-tracing/k8s-deployment

#### Describe the issue

Errors when applying the configuration

#### Recommended fix

The apiVersion extensions/v1beta1 needs to be changed to apps/v1
2nd need to add selector block in the deployments config spec section
e.g.
```
selector:
      matchLabels:
         app: jaeger
         app.kubernetes.io/name: jaeger
         app.kubernetes.io/component: agent
```
